/* ═══════════════════════════════════════════════════════════
   Meta Decks — Championship 2025-2026 Archetypes
   Curated top-tier decks across Standard, Pioneer, Modern
   ═══════════════════════════════════════════════════════════ */

const MetaDecks = [
  // ── STANDARD ────────────────────────────────────────────
  {
    name: "Azorius Control",
    format: "Standard",
    tier: 1,
    colors: ["W", "U"],
    description: "Dominant control shell using counterspells, board wipes, and planeswalkers. Won multiple Regional Championships in 2025-2026 season.",
    approxPrice: 280,
    cards: [
      { name: "No More Lies", qty: 4 }, { name: "Make Disappear", qty: 2 },
      { name: "Memory Deluge", qty: 3 }, { name: "The Wandering Emperor", qty: 3 },
      { name: "Sunfall", qty: 3 }, { name: "Depopulate", qty: 1 },
      { name: "Get Lost", qty: 4 }, { name: "Chrome Host Seedshark", qty: 3 },
      { name: "Restless Anchorage", qty: 4 }, { name: "Adarkar Wastes", qty: 4 },
      { name: "Deserted Beach", qty: 4 }, { name: "Plains", qty: 4 },
      { name: "Island", qty: 6 }, { name: "Lórien Revealed", qty: 2 },
      { name: "Deduce", qty: 4 }, { name: "Three Steps Ahead", qty: 2 },
      { name: "Elspeth's Smite", qty: 2 }, { name: "Temporary Lockdown", qty: 2 },
      { name: "Dovin's Veto", qty: 2 }, { name: "Absorption", qty: 2 },
    ],
    sideboard: [
      { name: "Rest in Peace", qty: 2 }, { name: "Disdainful Stroke", qty: 2 },
      { name: "Negate", qty: 2 }, { name: "Elspeth Resplendent", qty: 1 },
      { name: "Temporary Lockdown", qty: 1 }, { name: "Settle the Wreckage", qty: 2 },
      { name: "Mystical Dispute", qty: 2 }, { name: "Farewell", qty: 1 },
      { name: "Hullbreaker Horror", qty: 2 },
    ]
  },
  {
    name: "Gruul Aggro",
    format: "Standard",
    tier: 1,
    colors: ["R", "G"],
    description: "Fast aggressive deck leveraging efficient creatures and burn. Consistent top 8 performer at Arena Championships 2025-2026.",
    approxPrice: 220,
    cards: [
      { name: "Monastery Swiftspear", qty: 4 }, { name: "Kumano Faces Kakkazan", qty: 4 },
      { name: "Earthshaker Khenra", qty: 4 }, { name: "Bloodtithe Harvester", qty: 4 },
      { name: "Questing Druid", qty: 4 }, { name: "Pawblade Patrol", qty: 2 },
      { name: "Reckless Stormseeker", qty: 3 }, { name: "Lightning Strike", qty: 4 },
      { name: "Play with Fire", qty: 4 }, { name: "Monstrous Rage", qty: 4 },
      { name: "Karplusan Forest", qty: 4 }, { name: "Rockfall Vale", qty: 4 },
      { name: "Copperline Gorge", qty: 4 }, { name: "Mountain", qty: 6 },
      { name: "Forest", qty: 3 }, { name: "Sokenzan, Crucible of Defiance", qty: 2 },
    ],
    sideboard: [
      { name: "Torch the Tower", qty: 3 }, { name: "Abrade", qty: 2 },
      { name: "Roiling Vortex", qty: 2 }, { name: "Ulvenwald Oddity", qty: 2 },
      { name: "Lithomantic Barrage", qty: 2 }, { name: "End the Festivities", qty: 2 },
      { name: "Rending Flame", qty: 2 },
    ]
  },
  {
    name: "Dimir Midrange",
    format: "Standard",
    tier: 1,
    colors: ["U", "B"],
    description: "Flexible midrange strategy with removal, discard, and card advantage. Pro Tour staple across 2025-2026 season.",
    approxPrice: 350,
    cards: [
      { name: "Preacher of the Schism", qty: 4 }, { name: "Sheoldred, the Apocalypse", qty: 4 },
      { name: "Deep-Cavern Bat", qty: 4 }, { name: "Faerie Mastermind", qty: 3 },
      { name: "Go for the Throat", qty: 4 }, { name: "Cut Down", qty: 3 },
      { name: "Duress", qty: 2 }, { name: "Kaito Shizuki", qty: 2 },
      { name: "Aclazotz, Deepest Betrayal", qty: 2 }, { name: "Bitter Triumph", qty: 2 },
      { name: "Restless Reef", qty: 4 }, { name: "Underground River", qty: 4 },
      { name: "Shipwreck Marsh", qty: 4 }, { name: "Swamp", qty: 6 },
      { name: "Island", qty: 3 }, { name: "Darkslick Shores", qty: 4 },
      { name: "Virtue of Persistence", qty: 2 }, { name: "Lórien Revealed", qty: 2 },
    ],
    sideboard: [
      { name: "Negate", qty: 3 }, { name: "Duress", qty: 2 },
      { name: "Liliana of the Veil", qty: 2 }, { name: "Extinction Event", qty: 2 },
      { name: "Disdainful Stroke", qty: 2 }, { name: "Feed the Swarm", qty: 2 },
      { name: "Ashiok, Dream Render", qty: 2 },
    ]
  },
  {
    name: "Mono Red Burn",
    format: "Standard",
    tier: 2,
    colors: ["R"],
    description: "Pure speed. Cheapest competitive deck in Standard — all-in on dealing 20 damage fast with efficient burn spells and hasty creatures.",
    approxPrice: 120,
    cards: [
      { name: "Monastery Swiftspear", qty: 4 }, { name: "Play with Fire", qty: 4 },
      { name: "Lightning Strike", qty: 4 }, { name: "Kumano Faces Kakkazan", qty: 4 },
      { name: "Feldon, Ronom Excavator", qty: 4 }, { name: "Monstrous Rage", qty: 4 },
      { name: "Slickshot Show-Off", qty: 4 }, { name: "Scorching Shot", qty: 2 },
      { name: "Mountain", qty: 18 }, { name: "Sokenzan, Crucible of Defiance", qty: 2 },
      { name: "Ramunap Ruins", qty: 4 }, { name: "Shock", qty: 4 },
      { name: "Light Up the Stage", qty: 2 },
    ],
    sideboard: [
      { name: "Roiling Vortex", qty: 3 }, { name: "End the Festivities", qty: 3 },
      { name: "Abrade", qty: 3 }, { name: "Rending Flame", qty: 2 },
      { name: "Chandra, Dressed to Kill", qty: 2 }, { name: "Torch the Tower", qty: 2 },
    ]
  },

  // ── PIONEER ─────────────────────────────────────────────
  {
    name: "Rakdos Prowess",
    format: "Pioneer",
    tier: 1,
    colors: ["B", "R"],
    description: "The new king of Pioneer after dethroning Izzet Phoenix. Fast, consistent, and resilient with cheap threats and efficient removal.",
    approxPrice: 380,
    cards: [
      { name: "Monastery Swiftspear", qty: 4 }, { name: "Soul-Scar Mage", qty: 4 },
      { name: "Dreadhorde Arcanist", qty: 4 }, { name: "Bloodtithe Harvester", qty: 4 },
      { name: "Fatal Push", qty: 4 }, { name: "Thoughtseize", qty: 4 },
      { name: "Lightning Strike", qty: 4 }, { name: "Play with Fire", qty: 4 },
      { name: "Claim // Fame", qty: 2 }, { name: "Fiery Impulse", qty: 2 },
      { name: "Blood Crypt", qty: 4 }, { name: "Blightstep Pathway", qty: 4 },
      { name: "Blackcleave Cliffs", qty: 4 }, { name: "Mountain", qty: 6 },
      { name: "Swamp", qty: 2 }, { name: "Den of the Bugbear", qty: 2 },
      { name: "Monstrous Rage", qty: 2 },
    ],
    sideboard: [
      { name: "Duress", qty: 2 }, { name: "Unlicensed Hearse", qty: 2 },
      { name: "Rending Volley", qty: 2 }, { name: "Go Blank", qty: 2 },
      { name: "Kalitas, Traitor of Ghet", qty: 2 }, { name: "Kolaghan's Command", qty: 2 },
      { name: "Chandra, Torch of Defiance", qty: 1 }, { name: "Extinction Event", qty: 2 },
    ]
  },
  {
    name: "Izzet Phoenix",
    format: "Pioneer",
    tier: 1,
    colors: ["U", "R"],
    description: "Former Pioneer champion. Graveyard-powered synergy deck that recurs Arclight Phoenix with cheap cantrips.",
    approxPrice: 340,
    cards: [
      { name: "Arclight Phoenix", qty: 4 }, { name: "Thing in the Ice", qty: 4 },
      { name: "Ledger Shredder", qty: 4 }, { name: "Consider", qty: 4 },
      { name: "Opt", qty: 4 }, { name: "Lightning Axe", qty: 3 },
      { name: "Fiery Impulse", qty: 3 }, { name: "Treasure Cruise", qty: 2 },
      { name: "Temporal Trespass", qty: 1 }, { name: "Pieces of the Puzzle", qty: 3 },
      { name: "Chart a Course", qty: 2 }, { name: "Steam Vents", qty: 4 },
      { name: "Spirebluff Canal", qty: 4 }, { name: "Stormcarved Coast", qty: 4 },
      { name: "Island", qty: 5 }, { name: "Mountain", qty: 3 },
      { name: "Otawara, Soaring City", qty: 1 }, { name: "Galvanic Iteration", qty: 2 },
      { name: "Spell Pierce", qty: 2 }, { name: "Hall of Storm Giants", qty: 1 },
    ],
    sideboard: [
      { name: "Mystical Dispute", qty: 3 }, { name: "Negate", qty: 2 },
      { name: "Aether Gust", qty: 2 }, { name: "Brotherhood's End", qty: 2 },
      { name: "Young Pyromancer", qty: 2 }, { name: "Narset, Parter of Veils", qty: 1 },
      { name: "Disdainful Stroke", qty: 2 }, { name: "Crackling Drake", qty: 1 },
    ]
  },
  {
    name: "Mono Green Devotion",
    format: "Pioneer",
    tier: 2,
    colors: ["G"],
    description: "Ramp into powerful payoffs with Nykthos and devotion enablers. Can generate absurd mana and win with Cavalier or Storm the Festival.",
    approxPrice: 420,
    cards: [
      { name: "Elvish Mystic", qty: 4 }, { name: "Llanowar Elves", qty: 4 },
      { name: "Cavalier of Thorns", qty: 4 }, { name: "Old-Growth Troll", qty: 4 },
      { name: "Polukranos, World Eater", qty: 2 }, { name: "Storm the Festival", qty: 4 },
      { name: "Kiora, Behemoth Beckoner", qty: 3 }, { name: "Karn, the Great Creator", qty: 3 },
      { name: "Nykthos, Shrine to Nyx", qty: 4 }, { name: "Forest", qty: 14 },
      { name: "Lair of the Hydra", qty: 3 }, { name: "Castle Garenbrig", qty: 2 },
      { name: "Wolfwillow Haven", qty: 4 }, { name: "Burning-Tree Emissary", qty: 4 },
      { name: "Pestilent Cauldron", qty: 1 },
    ],
    sideboard: [
      { name: "Tormod's Crypt", qty: 1 }, { name: "Skysovereign, Consul Flagship", qty: 1 },
      { name: "God-Pharaoh's Statue", qty: 1 }, { name: "The Stone Brain", qty: 1 },
      { name: "Voracious Hydra", qty: 2 }, { name: "Reclamation Sage", qty: 2 },
      { name: "Hornet Queen", qty: 1 }, { name: "Boseiju, Who Endures", qty: 2 },
      { name: "Pithing Needle", qty: 1 }, { name: "Damping Sphere", qty: 1 },
      { name: "Cityscape Leveler", qty: 1 }, { name: "Portal to Phyrexia", qty: 1 },
    ]
  },
  {
    name: "Azorius Spirits",
    format: "Pioneer",
    tier: 2,
    colors: ["W", "U"],
    description: "Flash-speed tribal deck that disrupts opponents while building a board of evasive threats. Budget-friendly and competitive.",
    approxPrice: 200,
    cards: [
      { name: "Mausoleum Wanderer", qty: 4 }, { name: "Supreme Phantom", qty: 4 },
      { name: "Rattlechains", qty: 4 }, { name: "Shacklegeist", qty: 4 },
      { name: "Spell Queller", qty: 4 }, { name: "Empyrean Eagle", qty: 3 },
      { name: "Selfless Spirit", qty: 3 }, { name: "Curious Obsession", qty: 4 },
      { name: "Lofty Denial", qty: 3 }, { name: "Geistlight Snare", qty: 2 },
      { name: "Hallowed Fountain", qty: 4 }, { name: "Glacial Fortress", qty: 4 },
      { name: "Seachrome Coast", qty: 4 }, { name: "Island", qty: 5 },
      { name: "Plains", qty: 3 }, { name: "Eiganjo, Seat of the Empire", qty: 1 },
      { name: "Otawara, Soaring City", qty: 1 }, { name: "Brave the Elements", qty: 2 },
    ],
    sideboard: [
      { name: "Rest in Peace", qty: 2 }, { name: "Mystical Dispute", qty: 2 },
      { name: "Portable Hole", qty: 2 }, { name: "Settle the Wreckage", qty: 1 },
      { name: "Nebelgast Herald", qty: 2 }, { name: "Skyclave Apparition", qty: 2 },
      { name: "Dovin's Veto", qty: 2 }, { name: "Slip Out the Back", qty: 2 },
    ]
  },

  // ── MODERN ──────────────────────────────────────────────
  {
    name: "Boros Energy",
    format: "Modern",
    tier: 1,
    colors: ["W", "R"],
    description: "Aggressive energy-themed deck dominating Modern since late 2025. Efficient creatures backed by burn and energy payoffs.",
    approxPrice: 650,
    cards: [
      { name: "Guide of Souls", qty: 4 }, { name: "Amped Raptor", qty: 4 },
      { name: "Ocelot Pride", qty: 4 }, { name: "Phlage, Titan of Fire's Fury", qty: 4 },
      { name: "Ajani, Nacatl Pariah", qty: 4 }, { name: "Galvanic Discharge", qty: 4 },
      { name: "Lightning Bolt", qty: 4 }, { name: "Path to Exile", qty: 2 },
      { name: "Sacred Foundry", qty: 4 }, { name: "Inspiring Vantage", qty: 4 },
      { name: "Arid Mesa", qty: 4 }, { name: "Mountain", qty: 4 },
      { name: "Plains", qty: 4 }, { name: "Sunbaked Canyon", qty: 2 },
      { name: "Static Prison", qty: 4 }, { name: "Unstable Amulet", qty: 2 },
      { name: "Soulstone Sanctuary", qty: 2 },
    ],
    sideboard: [
      { name: "Wear // Tear", qty: 2 }, { name: "Rest in Peace", qty: 2 },
      { name: "Sanctifier en-Vec", qty: 2 }, { name: "Stony Silence", qty: 2 },
      { name: "Path to Exile", qty: 2 }, { name: "Chalice of the Void", qty: 2 },
      { name: "Engineered Explosives", qty: 1 }, { name: "Suncleanser", qty: 2 },
    ]
  },
  {
    name: "Golgari Yawgmoth",
    format: "Modern",
    tier: 1,
    colors: ["B", "G"],
    description: "Combo-midrange deck using Yawgmoth with undying creatures for value and infinite combos. Resilient and hard to interact with.",
    approxPrice: 720,
    cards: [
      { name: "Yawgmoth, Thran Physician", qty: 4 }, { name: "Young Wolf", qty: 4 },
      { name: "Strangleroot Geist", qty: 4 }, { name: "Blood Artist", qty: 2 },
      { name: "Geralf's Messenger", qty: 4 }, { name: "Elves of Deep Shadow", qty: 4 },
      { name: "Birds of Paradise", qty: 4 }, { name: "Chord of Calling", qty: 4 },
      { name: "Collected Company", qty: 4 }, { name: "Hapatra, Vizier of Poisons", qty: 2 },
      { name: "Overgrown Tomb", qty: 4 }, { name: "Blooming Marsh", qty: 4 },
      { name: "Verdant Catacombs", qty: 4 }, { name: "Forest", qty: 3 },
      { name: "Swamp", qty: 3 }, { name: "Nurturing Peatland", qty: 2 },
      { name: "Boseiju, Who Endures", qty: 2 }, { name: "Takenuma, Abandoned Mire", qty: 1 },
    ],
    sideboard: [
      { name: "Endurance", qty: 2 }, { name: "Force of Vigor", qty: 2 },
      { name: "Thoughtseize", qty: 3 }, { name: "Fatal Push", qty: 2 },
      { name: "Scavenging Ooze", qty: 1 }, { name: "Haywire Mite", qty: 1 },
      { name: "Necromentia", qty: 2 }, { name: "Outland Liberator", qty: 2 },
    ]
  },
  {
    name: "Jeskai Control",
    format: "Modern",
    tier: 2,
    colors: ["W", "U", "R"],
    description: "Classic draw-go control with Lightning Bolt, counterspells, and planeswalkers. Strong against creature-heavy metas.",
    approxPrice: 800,
    cards: [
      { name: "Lightning Bolt", qty: 4 }, { name: "Counterspell", qty: 4 },
      { name: "Prismatic Ending", qty: 3 }, { name: "Teferi, Time Raveler", qty: 4 },
      { name: "Narset, Parter of Veils", qty: 1 }, { name: "The One Ring", qty: 4 },
      { name: "Solitude", qty: 4 }, { name: "Subtlety", qty: 2 },
      { name: "Supreme Verdict", qty: 2 }, { name: "Memory Deluge", qty: 2 },
      { name: "Flooded Strand", qty: 4 }, { name: "Scalding Tarn", qty: 4 },
      { name: "Hallowed Fountain", qty: 2 }, { name: "Steam Vents", qty: 2 },
      { name: "Sacred Foundry", qty: 1 }, { name: "Island", qty: 4 },
      { name: "Plains", qty: 1 }, { name: "Mountain", qty: 1 },
      { name: "Raugrin Triome", qty: 1 }, { name: "Celestial Colonnade", qty: 2 },
      { name: "Spell Pierce", qty: 2 }, { name: "Dress Down", qty: 1 },
    ],
    sideboard: [
      { name: "Flusterstorm", qty: 2 }, { name: "Wear // Tear", qty: 2 },
      { name: "Rest in Peace", qty: 2 }, { name: "Engineered Explosives", qty: 1 },
      { name: "Jace, the Mind Sculptor", qty: 1 }, { name: "Chalice of the Void", qty: 2 },
      { name: "Mystical Dispute", qty: 2 }, { name: "Supreme Verdict", qty: 1 },
      { name: "Shark Typhoon", qty: 2 },
    ]
  },
  {
    name: "4c Omnath",
    format: "Modern",
    tier: 1,
    colors: ["W", "U", "R", "G"],
    description: "Elementals-based value pile abusing Omnath landfall triggers with fetchlands. Generates overwhelming card advantage.",
    approxPrice: 950,
    cards: [
      { name: "Omnath, Locus of Creation", qty: 4 }, { name: "Solitude", qty: 4 },
      { name: "Fury", qty: 2 }, { name: "Endurance", qty: 2 },
      { name: "Teferi, Time Raveler", qty: 3 }, { name: "Wrenn and Six", qty: 4 },
      { name: "The One Ring", qty: 4 }, { name: "Lightning Bolt", qty: 4 },
      { name: "Prismatic Ending", qty: 2 }, { name: "Counterspell", qty: 2 },
      { name: "Misty Rainforest", qty: 4 }, { name: "Windswept Heath", qty: 4 },
      { name: "Flooded Strand", qty: 2 }, { name: "Steam Vents", qty: 1 },
      { name: "Hallowed Fountain", qty: 1 }, { name: "Temple Garden", qty: 1 },
      { name: "Sacred Foundry", qty: 1 }, { name: "Breeding Pool", qty: 1 },
      { name: "Raugrin Triome", qty: 1 }, { name: "Ketria Triome", qty: 1 },
      { name: "Forest", qty: 1 }, { name: "Island", qty: 1 },
      { name: "Plains", qty: 1 }, { name: "Mountain", qty: 1 },
      { name: "Boseiju, Who Endures", qty: 1 }, { name: "Abundant Growth", qty: 4 },
      { name: "Leyline Binding", qty: 3 },
    ],
    sideboard: [
      { name: "Flusterstorm", qty: 2 }, { name: "Force of Vigor", qty: 2 },
      { name: "Veil of Summer", qty: 2 }, { name: "Supreme Verdict", qty: 2 },
      { name: "Wear // Tear", qty: 1 }, { name: "Engineered Explosives", qty: 1 },
      { name: "Subtlety", qty: 2 }, { name: "Dress Down", qty: 1 },
      { name: "Kaheera, the Orphanguard", qty: 1 }, { name: "Chalice of the Void", qty: 1 },
    ]
  },
];
